/**
 * The app icon's shipping constraints, pinned.
 *
 * Two failures these guard against, both of which are invisible locally and
 * only surface as an App Store rejection or a wrong-looking home screen:
 *
 * 1. **Transparency in the iOS icon.** Apple rejects an app icon carrying an
 *    alpha channel. Nothing in the build warns about it, and the icon looks
 *    correct everywhere until the binary is validated.
 *
 * 2. **Shipping the stock Expo placeholder.** `assets/icon.png` was the
 *    default grey-circles placeholder from project creation until 2026-09-19 —
 *    it sat there through the first iOS build without appearing on any
 *    checklist. The placeholder is a palette-mode PNG (colour type 3), so the
 *    colour-type assertion below fails if it is ever restored.
 *
 * The icons are generated by `assets/source/make-icons.py`; this reads the
 * committed PNGs directly rather than the generator, because what ships is the
 * PNG. PNG headers are parsed by hand — width, height and colour type all live
 * at fixed offsets in the IHDR chunk — to avoid adding an image dependency for
 * four assertions.
 */
const fs = require('fs');
const path = require('path');

const PNG_SIGNATURE = Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]);

// IHDR is always the first chunk: 8-byte signature, 4-byte length, 4-byte type,
// then width, height, bit depth, colour type.
const COLOUR_TYPE = { GREY: 0, RGB: 2, PALETTE: 3, GREY_ALPHA: 4, RGBA: 6 };

function readPng(name) {
  const buf = fs.readFileSync(path.join(__dirname, '..', 'assets', name));
  if (!buf.subarray(0, 8).equals(PNG_SIGNATURE)) {
    throw new Error(`${name} is not a PNG`);
  }
  if (buf.subarray(12, 16).toString('ascii') !== 'IHDR') {
    throw new Error(`${name}: first chunk is not IHDR`);
  }
  return {
    width: buf.readUInt32BE(16),
    height: buf.readUInt32BE(20),
    colourType: buf[25],
    bytes: buf.length,
  };
}

describe('app icon assets', () => {
  test('icon.png is 1024x1024 and carries NO alpha channel (iOS rejects alpha)', () => {
    const icon = readPng('icon.png');
    expect([icon.width, icon.height]).toEqual([1024, 1024]);
    expect(icon.colourType).toBe(COLOUR_TYPE.RGB);
  });

  test('adaptive-icon.png is 1024x1024 with alpha (Android supplies the background)', () => {
    const adaptive = readPng('adaptive-icon.png');
    expect([adaptive.width, adaptive.height]).toEqual([1024, 1024]);
    expect(adaptive.colourType).toBe(COLOUR_TYPE.RGBA);
  });

  test('splash-icon.png is 1024x1024', () => {
    const splash = readPng('splash-icon.png');
    expect([splash.width, splash.height]).toEqual([1024, 1024]);
  });

  test('favicon.png is 48x48', () => {
    const favicon = readPng('favicon.png');
    expect([favicon.width, favicon.height]).toEqual([48, 48]);
  });

  // The Android half fails SILENTLY. Because this project commits its
  // android/ folder, EAS Build does not sync `icon` from app.json (the one
  // expo-doctor check this repo knowingly fails), so changing
  // assets/icon.png alone updates iOS and leaves Android on the previously
  // committed launcher icons. These pin the density ladder so a half-done
  // icon change is caught here instead of on someone's phone.
  //
  // The files are named *.webp but hold PNG data — that is what Expo's
  // prebuild wrote and what the build already accepts. If that ever changes
  // deliberately, this test is the right place to notice.
  describe.each([
    ['mdpi', 48, 108],
    ['hdpi', 72, 162],
    ['xhdpi', 96, 216],
    ['xxhdpi', 144, 324],
    ['xxxhdpi', 192, 432],
  ])('android mipmap-%s', (density, launcher, foreground) => {
    const dir = path.join(
      __dirname, '..', 'android/app/src/main/res', `mipmap-${density}`);

    function readAndroidPng(name) {
      const buf = fs.readFileSync(path.join(dir, name));
      if (!buf.subarray(0, 8).equals(PNG_SIGNATURE)) {
        throw new Error(`${density}/${name} is no longer PNG data — see the note above`);
      }
      return { width: buf.readUInt32BE(16), height: buf.readUInt32BE(20) };
    }

    test(`ic_launcher is ${launcher}px and ic_launcher_round matches`, () => {
      expect(readAndroidPng('ic_launcher.webp')).toEqual({
        width: launcher, height: launcher });
      expect(readAndroidPng('ic_launcher_round.webp')).toEqual({
        width: launcher, height: launcher });
    });

    test(`ic_launcher_foreground is ${foreground}px`, () => {
      expect(readAndroidPng('ic_launcher_foreground.webp')).toEqual({
        width: foreground, height: foreground });
    });
  });

  test('app.json points at the icons that exist', () => {
    const { expo } = require('../app.json');
    const referenced = [
      expo.icon,
      expo.splash.image,
      expo.android.adaptiveIcon.foregroundImage,
    ];
    for (const ref of referenced) {
      expect(ref).toMatch(/^\.\/assets\//);
      expect(fs.existsSync(path.join(__dirname, '..', ref))).toBe(true);
    }
  });
});
